### Setup

In [1]:
from main_functions.utils import read_grid_search

### Check results - Tsinghua Dataset

#### k-fold DFT (1 subject)

##### Subject 1

In [20]:
dft_kfold = read_grid_search("results_v3/tsinghua_1_DFT_4_Sum_kfold_1")
dft_kfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Pooling,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy,Time,Params
1809,DFT,500,10,Sum,"(0.2, 0.2)",1.0,0.100,0.5,3,2,1,1,"(1, 8, 16, 4)",opt8,0.0040,0.82,21.06,54220
664,DFT,500,10,Sum,"(0.5, 0.5)",0.0,0.100,0.5,3,2,1,2,"(1, 8, 8, 4)",opt3,0.0100,0.80,20.68,27044
1853,DFT,500,10,Sum,"(0.6, 0.2)",0.0,0.001,0.5,2,1,2,1,"(1, 8, 8, 4)",opt5,0.0100,0.78,28.55,71828
1750,DFT,500,10,Sum,"(0.3, 0.15)",0.0,0.100,0.5,3,2,1,2,"(1, 8, 8, 4)",opt4,0.0040,0.78,21.39,27044
2002,DFT,500,10,Sum,"(0.3, 0.5)",0.0,0.001,0.5,2,1,1,1,"(1, 8, 8, 4)",opt4,0.0100,0.78,27.90,36116
648,DFT,500,10,Sum,"(0.3, 0.15)",0.0,0.001,0.5,3,2,1,2,"(1, 8, 8, 4)",opt3,0.0100,0.78,21.66,27044
1140,DFT,500,10,Sum,"(0.3, 0.15)",1.0,0.010,0.5,3,2,1,2,"(1, 8, 16, 4)",opt5,0.0002,0.76,21.37,27148
875,DFT,500,10,Sum,"(0.6, 0.2)",0.0,0.100,0.5,2,1,1,1,"(1, 8, 16, 4)",opt3,0.0100,0.76,28.48,36220
1510,DFT,500,10,Sum,"(0.2, 0.2)",0.0,0.010,0.5,2,1,2,1,"(1, 16, 16, 4)",opt3,0.0100,0.76,28.58,135812
871,DFT,500,10,Sum,"(0.5, 0.5)",1.0,0.001,0.5,3,2,2,1,"(1, 8, 16, 4)",opt8,0.0040,0.76,21.64,107788

In [8]:
dft_kfold.shape[0]

2085

##### Subject 4

In [21]:
# taking abs(DHT(original signal))
dft_kfold4 = read_grid_search("results_v3/tsinghua_4_DFT_4_Sum_kfold_1") #grid_search_1_DHT_top10_4_kfold
dft_kfold4.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Pooling,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy,Time,Params
2002,DFT,500,10,Sum,"(0.6, 0.2)",0.0,0.010,0.5,2,1,1,1,"(1, 16, 16, 4)",opt8,0.010,0.86,27.42,68356
249,DFT,500,10,Sum,"(0.2, 0.2)",0.0,0.100,0.5,2,1,1,1,"(1, 4, 8, 4)",opt4,0.004,0.84,28.25,20080
394,DFT,500,10,Sum,"(0.3, 0.5)",0.0,0.010,0.5,2,1,1,4,"(1, 4, 8, 4)",opt4,0.004,0.82,28.06,5040
1233,DFT,500,10,Sum,"(0.3, 0.15)",0.0,0.100,0.5,2,1,1,5,"(1, 8, 16, 4)",opt3,0.010,0.82,27.61,7420
1544,DFT,500,10,Sum,"(0.3, 0.5)",0.0,0.001,0.5,2,1,1,1,"(1, 8, 8, 4)",opt4,0.010,0.82,28.76,36116
1820,DFT,500,10,Sum,"(0.3, 0.5)",2.0,0.100,0.5,2,1,1,1,"(1, 16, 16, 4)",opt8,0.004,0.82,27.49,68356
1575,DFT,500,10,Sum,"(0.5, 0.5)",0.0,0.010,0.5,2,1,1,3,"(1, 4, 8, 4)",opt4,0.010,0.82,28.09,6720
142,DFT,500,10,Sum,"(0.3, 0.5)",2.0,0.001,0.5,2,1,3,1,"(1, 16, 16, 4)",opt8,0.004,0.82,27.42,201092
932,DFT,500,10,Sum,"(0.6, 0.2)",2.0,0.010,0.5,2,1,1,1,"(1, 8, 16, 4)",opt8,0.004,0.80,28.10,36220
1162,DFT,500,10,Sum,"(0.6, 0.2)",0.0,0.010,0.5,2,1,1,4,"(1, 4, 8, 4)",opt3,0.010,0.80,28.30,5040

##### Subject 11

In [2]:
dft11_kfold = read_grid_search("results/tsinghua_11_DFT_4_kfold_1")
dft11_kfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
18160,DFT,500,10,"(0.3, 0.5)",0.0,0.010,0.5,3,2,2,1,"(1, 8, 16, 4)",opt8,0.004,0.80
16171,DFT,500,10,"(0.6, 0.2)",0.0,0.010,0.5,3,2,2,1,"(1, 8, 16, 4)",opt8,0.004,0.80
20490,DFT,500,10,"(0.5, 0.5)",0.0,0.001,0.5,3,2,2,1,"(1, 8, 16, 4)",opt8,0.010,0.78
10643,DFT,500,10,"(0.6, 0.2)",0.0,0.010,0.5,3,2,3,1,"(1, 8, 16, 4)",opt8,0.010,0.74
15242,DFT,500,10,"(0.6, 0.2)",0.0,0.010,0.5,3,2,1,1,"(1, 8, 16, 4)",opt8,0.004,0.74
11709,DFT,500,10,"(0.3, 0.15)",0.0,0.010,0.5,3,2,1,1,"(1, 8, 16, 4)",opt8,0.004,0.74
9620,DFT,500,10,"(0.3, 0.5)",0.0,0.010,0.5,3,2,2,1,"(1, 16, 16, 4)",opt8,0.010,0.72
611,DFT,500,10,"(0.2, 0.2)",0.0,0.001,0.5,3,2,3,1,"(1, 8, 8, 4)",opt8,0.010,0.70
12641,DFT,500,10,"(0.3, 0.5)",0.0,0.010,0.5,3,2,1,1,"(1, 16, 16, 4)",opt8,0.010,0.70
2630,DFT,500,10,"(0.5, 0.5)",0.0,0.010,0.5,3,2,1,1,"(1, 16, 16, 4)",opt8,0.004,0.70

In [3]:
dft11_kfold.shape[0]

21400

In [19]:
print(dft11_kfold.sort_values("Mean_Accuracy",ascending=False).head(10).to_latex(caption='Results of k-fold cross validation over trials for subject 11.'))

\begin{table}
\centering
\caption{Results of k-fold cross validation over trials for subject 11.}
\begin{tabular}{llrrlrrrrrrrllrr}
\toprule
{} & Function &  Epochs &  Batch\_Size &      Dropout &  FreqMean &  FreqStd &  Time\_Off &  Window &  Overlap &  Levels &  Band\_Width & Neuron\_Configuration & Optimizer &  Learning\_Rate &  Mean\_Accuracy \\
\midrule
18160 &      DFT &     500 &          10 &   (0.3, 0.5) &       0.0 &    0.010 &       0.5 &       3 &        2 &       2 &           1 &        (1, 8, 16, 4) &      opt8 &          0.004 &           0.80 \\
16171 &      DFT &     500 &          10 &   (0.6, 0.2) &       0.0 &    0.010 &       0.5 &       3 &        2 &       2 &           1 &        (1, 8, 16, 4) &      opt8 &          0.004 &           0.80 \\
20490 &      DFT &     500 &          10 &   (0.5, 0.5) &       0.0 &    0.001 &       0.5 &       3 &        2 &       2 &           1 &        (1, 8, 16, 4) &      opt8 &          0.010 &           0.78 \\
10643 &      DFT &     500 &          10 &   (0.6, 0.2) &       0.0 &    0.010 &       0.5 &       3 &        2 &       3 &           1 &        (1, 8, 16, 4) &      opt8 &          0.010 &           0.74 \\
15242 &      DFT &     500 &          10 &   (0.6, 0.2) &       0.0 &    0.010 &       0.5 &       3 &        2 &       1 &           1 &        (1, 8, 16, 4) &      opt8 &          0.004 &           0.74 \\
11709 &      DFT &     500 &          10 &  (0.3, 0.15) &       0.0 &    0.010 &       0.5 &       3 &        2 &       1 &           1 &        (1, 8, 16, 4) &      opt8 &          0.004 &           0.74 \\
9620  &      DFT &     500 &          10 &   (0.3, 0.5) &       0.0 &    0.010 &       0.5 &       3 &        2 &       2 &           1 &       (1, 16, 16, 4) &      opt8 &          0.010 &           0.72 \\
611   &      DFT &     500 &          10 &   (0.2, 0.2) &       0.0 &    0.001 &       0.5 &       3 &        2 &       3 &           1 &         (1, 8, 8, 4) &      opt8 &          0.010 &           0.70 \\
12641 &      DFT &     500 &          10 &   (0.3, 0.5) &       0.0 &    0.010 &       0.5 &       3 &        2 &       1 &           1 &       (1, 16, 16, 4) &      opt8 &          0.010 &           0.70 \\
2630  &      DFT &     500 &          10 &   (0.5, 0.5) &       0.0 &    0.010 &       0.5 &       3 &        2 &       1 &           1 &       (1, 16, 16, 4) &      opt8 &          0.004 &           0.70 \\
\bottomrule
\end{tabular}
\end{table}

/tmp/ipykernel_3507/4235933666.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(dft11_kfold.sort_values("Mean_Accuracy",ascending=False).head(10).to_latex(caption='Results of k-fold cross validation over trials for subject 11.'))

In [2]:
halfdft_kfold = read_grid_search("results/tsinghua_11_halfDFT_4_kfold_1") #grid_search_1_DHT_top10_4_kfold
halfdft_kfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
6686,halfDFT,500,10,"(0.3, 0.15)",0.0,0.010,0.5,3,2,1,1,"(1, 8, 16, 4)",opt8,0.004,0.80
8762,halfDFT,500,10,"(0.6, 0.2)",0.0,0.010,0.5,3,2,1,1,"(1, 8, 16, 4)",opt8,0.004,0.80
8525,halfDFT,500,10,"(0.2, 0.2)",0.0,0.010,0.5,3,2,3,1,"(1, 16, 16, 4)",opt8,0.010,0.78
11780,halfDFT,500,10,"(0.5, 0.5)",0.0,0.001,0.5,3,2,2,1,"(1, 8, 16, 4)",opt8,0.010,0.76
6094,halfDFT,500,10,"(0.6, 0.2)",0.0,0.010,0.5,3,2,3,1,"(1, 8, 16, 4)",opt8,0.010,0.74
4429,halfDFT,500,10,"(0.3, 0.15)",0.0,0.100,0.5,3,2,3,1,"(1, 8, 16, 4)",opt8,0.004,0.62
1049,halfDFT,500,10,"(0.3, 0.15)",0.0,0.001,0.5,3,2,2,1,"(1, 4, 8, 4)",opt8,0.004,0.58
8408,halfDFT,500,10,"(0.3, 0.5)",0.0,0.010,0.5,2,1,1,1,"(1, 4, 8, 4)",opt8,0.010,0.58
2797,halfDFT,500,10,"(0.3, 0.5)",0.0,0.010,0.5,2,1,1,1,"(1, 4, 8, 4)",opt8,0.004,0.58
5926,halfDFT,500,10,"(0.5, 0.5)",0.0,0.100,0.5,3,2,1,1,"(1, 4, 8, 4)",opt8,0.010,0.58

In [3]:
halfdft_kfold.shape[0]

12312

#### k-fold DHT (1 subject)

##### Subject 1

In [25]:
# taking abs(DHT(original signal))
dht_kfold = read_grid_search("results_v3/tsinghua_1_DHT_4_Sum_kfold_1") #grid_search_1_DHT_top10_4_kfold
dht_kfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Pooling,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy,Time,Params
1308,DHT,500,10,Sum,"(0.5, 0.5)",0.0,0.010,0.5,3,2,1,1,"(1, 8, 8, 4)",opt5,0.004,0.82,21.68,54116
541,DHT,500,10,Sum,"(0.3, 0.5)",0.0,0.100,0.5,3,2,1,1,"(1, 16, 16, 4)",opt3,0.010,0.78,21.59,102356
1093,DHT,500,10,Sum,"(0.3, 0.5)",0.0,0.010,0.5,2,1,1,1,"(1, 8, 8, 4)",opt7,0.010,0.76,28.32,36116
409,DHT,500,10,Sum,"(0.2, 0.2)",1.0,0.001,0.5,3,2,1,1,"(1, 16, 16, 4)",opt5,0.001,0.76,21.50,102356
1886,DHT,500,10,Sum,"(0.3, 0.15)",0.0,0.100,0.5,3,2,1,2,"(1, 16, 16, 4)",opt7,0.001,0.76,21.51,51220
1855,DHT,500,10,Sum,"(0.3, 0.5)",0.0,0.100,0.5,3,2,1,2,"(1, 16, 16, 4)",opt5,0.004,0.76,21.60,51220
1687,DHT,500,10,Sum,"(0.6, 0.2)",1.0,0.001,0.5,3,2,1,1,"(1, 16, 16, 4)",opt5,0.001,0.76,21.95,102356
222,DHT,500,10,Sum,"(0.2, 0.2)",1.0,0.001,0.5,3,2,1,1,"(1, 16, 16, 4)",opt7,0.010,0.76,20.72,102356
21,DHT,500,10,Sum,"(0.2, 0.2)",0.0,0.100,0.5,3,2,2,1,"(1, 8, 8, 4)",opt7,0.010,0.74,21.25,107684
141,DHT,500,10,Sum,"(0.3, 0.15)",0.0,0.001,0.5,3,2,2,1,"(1, 16, 16, 4)",opt4,0.004,0.74,22.00,203540

In [11]:
dht_kfold.shape[0]

2062

##### Subject 4

In [24]:
# taking abs(DHT(original signal))
dht_kfold4 = read_grid_search("results_v3/tsinghua_4_DHT_4_Sum_kfold_1") #grid_search_1_DHT_top10_4_kfold
dht_kfold4.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Pooling,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy,Time,Params
1215,DHT,500,10,Sum,"(0.3, 0.5)",0.0,0.100,0.5,2,1,3,1,"(1, 8, 8, 4)",opt7,0.010,0.82,28.38,106388
1356,DHT,500,10,Sum,"(0.3, 0.5)",1.0,0.001,0.5,3,2,1,5,"(1, 16, 16, 4)",opt7,0.010,0.80,21.47,20756
1652,DHT,500,10,Sum,"(0.6, 0.2)",1.0,0.001,0.5,3,2,1,5,"(1, 16, 16, 4)",opt7,0.010,0.80,21.66,20756
480,DHT,500,10,Sum,"(0.3, 0.5)",0.0,0.001,0.5,2,1,1,4,"(1, 4, 8, 4)",opt7,0.004,0.80,28.53,5040
1668,DHT,500,10,Sum,"(0.5, 0.5)",0.0,0.010,0.5,2,1,3,1,"(1, 16, 16, 4)",opt4,0.010,0.78,29.00,201092
547,DHT,500,10,Sum,"(0.2, 0.2)",1.0,0.001,0.5,3,2,1,5,"(1, 8, 16, 4)",opt5,0.004,0.78,21.24,11020
1490,DHT,500,10,Sum,"(0.5, 0.5)",0.0,0.010,0.5,2,1,2,1,"(1, 8, 16, 4)",opt4,0.010,0.78,28.64,71932
792,DHT,500,10,Sum,"(0.3, 0.15)",0.0,0.010,0.5,2,1,3,1,"(1, 16, 16, 4)",opt7,0.010,0.78,28.21,201092
1033,DHT,500,10,Sum,"(0.6, 0.2)",0.0,0.001,0.5,2,1,1,4,"(1, 4, 8, 4)",opt4,0.010,0.78,28.01,5040
1487,DHT,500,10,Sum,"(0.2, 0.2)",1.0,0.001,0.5,3,2,1,5,"(1, 8, 16, 4)",opt3,0.004,0.78,21.58,11020

##### Subject 11

In [4]:
dht11_kfold = read_grid_search("results/tsinghua_11_DHT_4_kfold_1") #grid_search_1_DHT_top10_4_kfold
dht11_kfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
10675,DHT,500,10,"(0.6, 0.2)",0.0,0.001,0.5,3,2,3,1,"(1, 8, 16, 4)",opt8,0.010,0.74
7015,DHT,500,10,"(0.3, 0.15)",0.0,0.010,0.5,3,2,3,1,"(1, 8, 16, 4)",opt8,0.010,0.70
3763,DHT,500,10,"(0.2, 0.2)",0.0,0.001,0.5,3,2,2,1,"(1, 8, 16, 4)",opt8,0.010,0.68
3773,DHT,500,10,"(0.6, 0.2)",0.0,0.010,0.5,2,1,1,1,"(1, 16, 16, 4)",opt8,0.010,0.64
483,DHT,500,10,"(0.5, 0.5)",0.0,0.001,0.5,2,1,2,2,"(1, 16, 16, 4)",opt8,0.004,0.60
17,DHT,500,10,"(0.5, 0.5)",0.0,0.010,0.5,2,1,2,1,"(1, 16, 16, 4)",opt8,0.010,0.58
14336,DHT,500,10,"(0.3, 0.15)",0.0,0.001,0.5,2,1,3,1,"(1, 4, 8, 4)",opt8,0.010,0.56
20505,DHT,500,10,"(0.5, 0.5)",0.0,0.010,0.5,3,2,3,1,"(1, 8, 8, 4)",opt8,0.010,0.56
19981,DHT,500,10,"(0.6, 0.2)",0.0,0.010,0.5,3,2,3,1,"(1, 4, 8, 4)",opt8,0.010,0.56
7488,DHT,500,10,"(0.3, 0.15)",0.0,0.010,0.5,2,1,3,1,"(1, 8, 16, 4)",opt8,0.004,0.54

In [9]:
dht11_kfold.shape[0]

21491

In [20]:
print(dht11_kfold.sort_values("Mean_Accuracy",ascending=False).head(10).to_latex(caption='Results of k-fold cross validation over trials for subject 11.'))

\begin{table}
\centering
\caption{Results of k-fold cross validation over trials for subject 11.}
\begin{tabular}{llrrlrrrrrrrllrr}
\toprule
{} & Function &  Epochs &  Batch\_Size &      Dropout &  FreqMean &  FreqStd &  Time\_Off &  Window &  Overlap &  Levels &  Band\_Width & Neuron\_Configuration & Optimizer &  Learning\_Rate &  Mean\_Accuracy \\
\midrule
10675 &      DHT &     500 &          10 &   (0.6, 0.2) &       0.0 &    0.001 &       0.5 &       3 &        2 &       3 &           1 &        (1, 8, 16, 4) &      opt8 &          0.010 &           0.74 \\
7015  &      DHT &     500 &          10 &  (0.3, 0.15) &       0.0 &    0.010 &       0.5 &       3 &        2 &       3 &           1 &        (1, 8, 16, 4) &      opt8 &          0.010 &           0.70 \\
3763  &      DHT &     500 &          10 &   (0.2, 0.2) &       0.0 &    0.001 &       0.5 &       3 &        2 &       2 &           1 &        (1, 8, 16, 4) &      opt8 &          0.010 &           0.68 \\
3773  &      DHT &     500 &          10 &   (0.6, 0.2) &       0.0 &    0.010 &       0.5 &       2 &        1 &       1 &           1 &       (1, 16, 16, 4) &      opt8 &          0.010 &           0.64 \\
483   &      DHT &     500 &          10 &   (0.5, 0.5) &       0.0 &    0.001 &       0.5 &       2 &        1 &       2 &           2 &       (1, 16, 16, 4) &      opt8 &          0.004 &           0.60 \\
17    &      DHT &     500 &          10 &   (0.5, 0.5) &       0.0 &    0.010 &       0.5 &       2 &        1 &       2 &           1 &       (1, 16, 16, 4) &      opt8 &          0.010 &           0.58 \\
14336 &      DHT &     500 &          10 &  (0.3, 0.15) &       0.0 &    0.001 &       0.5 &       2 &        1 &       3 &           1 &         (1, 4, 8, 4) &      opt8 &          0.010 &           0.56 \\
20505 &      DHT &     500 &          10 &   (0.5, 0.5) &       0.0 &    0.010 &       0.5 &       3 &        2 &       3 &           1 &         (1, 8, 8, 4) &      opt8 &          0.010 &           0.56 \\
19981 &      DHT &     500 &          10 &   (0.6, 0.2) &       0.0 &    0.010 &       0.5 &       3 &        2 &       3 &           1 &         (1, 4, 8, 4) &      opt8 &          0.010 &           0.56 \\
7488  &      DHT &     500 &          10 &  (0.3, 0.15) &       0.0 &    0.010 &       0.5 &       2 &        1 &       3 &           1 &        (1, 8, 16, 4) &      opt8 &          0.004 &           0.54 \\
\bottomrule
\end{tabular}
\end{table}

/tmp/ipykernel_3507/2827937377.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(dht11_kfold.sort_values("Mean_Accuracy",ascending=False).head(10).to_latex(caption='Results of k-fold cross validation over trials for subject 11.'))

In [2]:
halfdht_kfold = read_grid_search("results/tsinghua_11_halfDHT_4_kfold_1") #neither arcsinh or flip
halfdht_kfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
5650,halfDHT,500,10,"(0.3, 0.15)",0.0,0.010,0.5,3,2,3,1,"(1, 8, 16, 4)",opt8,0.0100,0.62
8663,halfDHT,500,10,"(0.6, 0.2)",0.0,0.001,0.5,3,2,3,1,"(1, 8, 16, 4)",opt8,0.0100,0.62
14732,halfDHT,500,10,"(0.3, 0.5)",2.0,0.010,0.5,3,2,2,1,"(1, 8, 16, 4)",opt8,0.0040,0.58
3025,halfDHT,500,10,"(0.2, 0.2)",0.0,0.001,0.5,3,2,2,1,"(1, 8, 16, 4)",opt8,0.0100,0.58
15902,halfDHT,500,10,"(0.2, 0.2)",1.0,0.001,0.5,3,2,2,1,"(1, 8, 16, 4)",opt8,0.0010,0.56
15872,halfDHT,500,10,"(0.3, 0.15)",2.0,0.010,0.5,3,2,2,1,"(1, 8, 8, 4)",opt8,0.0001,0.56
3876,halfDHT,500,10,"(0.3, 0.5)",2.0,0.010,0.5,3,2,2,1,"(1, 8, 16, 4)",opt8,0.0010,0.54
4954,halfDHT,500,10,"(0.5, 0.5)",1.0,0.001,0.5,3,2,2,1,"(1, 8, 16, 4)",opt8,0.0040,0.54
12058,halfDHT,500,10,"(0.2, 0.2)",0.0,0.100,0.5,3,2,3,1,"(1, 16, 16, 4)",opt8,0.0100,0.54
6536,halfDHT,500,10,"(0.5, 0.5)",2.0,0.010,0.5,3,2,3,1,"(1, 8, 8, 4)",opt8,0.0002,0.54

In [3]:
halfdht_kfold.shape[0]

17301

In [4]:
# here I'm starting to flip the input data
dhtflip_kfold = read_grid_search("results/tsinghua_11_dataDHTflip_4_kfold_1") #grid_search_1_DHT_top10_4_kfold
dhtflip_kfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
14847,dataDHTflip,500,10,"(0.2, 0.2)",0.0,0.010,0.5,3,2,1,4,"(1, 8, 16, 4)",opt8,0.0100,0.50
14426,dataDHTflip,500,10,"(0.2, 0.2)",2.0,0.001,0.5,3,2,3,1,"(1, 8, 8, 4)",opt3,0.0001,0.50
10022,dataDHTflip,500,10,"(0.3, 0.5)",2.0,0.010,0.5,3,2,3,1,"(1, 8, 8, 4)",opt3,0.0001,0.50
4855,dataDHTflip,500,10,"(0.3, 0.15)",2.0,0.010,0.5,2,1,1,1,"(1, 4, 8, 4)",opt4,0.0001,0.48
16222,dataDHTflip,500,10,"(0.3, 0.15)",2.0,0.010,0.5,3,2,2,2,"(1, 16, 16, 4)",opt5,0.0040,0.48
243,dataDHTflip,500,10,"(0.6, 0.2)",0.0,0.010,0.5,3,2,2,2,"(1, 4, 8, 4)",opt8,0.0100,0.48
8943,dataDHTflip,500,10,"(0.6, 0.2)",0.0,0.100,0.5,3,2,1,5,"(1, 8, 8, 4)",opt7,0.0100,0.48
10563,dataDHTflip,500,10,"(0.3, 0.5)",2.0,0.010,0.5,3,2,2,2,"(1, 16, 16, 4)",opt5,0.0040,0.48
1639,dataDHTflip,500,10,"(0.6, 0.2)",1.0,0.100,0.5,2,1,2,3,"(1, 4, 8, 4)",opt1,0.0010,0.48
10970,dataDHTflip,500,10,"(0.5, 0.5)",0.0,0.010,0.5,3,2,2,2,"(1, 4, 8, 4)",opt8,0.0100,0.48

In [5]:
dhtflip_kfold.shape[0]

16382

In [4]:
symhalfdht_kfold = read_grid_search("results/tsinghua_11_symDHT_4_kfold_1") #using arcsinh and abs and flip
symhalfdht_kfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
12985,symDHT,500,10,"(0.2, 0.2)",2.0,0.100,0.5,2,1,1,4,"(1, 16, 16, 4)",opt8,0.0010,0.48
16684,symDHT,500,10,"(0.6, 0.2)",1.0,0.001,0.5,2,1,1,4,"(1, 16, 16, 4)",opt8,0.0001,0.48
9810,symDHT,500,10,"(0.6, 0.2)",1.0,0.001,0.5,2,1,1,4,"(1, 16, 16, 4)",opt4,0.0010,0.46
10862,symDHT,500,10,"(0.2, 0.2)",2.0,0.100,0.5,2,1,1,4,"(1, 16, 16, 4)",opt4,0.0002,0.46
7599,symDHT,500,10,"(0.5, 0.5)",1.0,0.001,0.5,2,1,1,4,"(1, 16, 16, 4)",opt4,0.0010,0.46
12790,symDHT,500,10,"(0.2, 0.2)",2.0,0.100,0.5,2,1,1,4,"(1, 16, 16, 4)",opt5,0.0002,0.46
9073,symDHT,500,10,"(0.5, 0.5)",2.0,0.100,0.5,2,1,1,4,"(1, 16, 16, 4)",opt5,0.0002,0.46
551,symDHT,500,10,"(0.3, 0.5)",2.0,0.001,0.5,3,2,3,5,"(1, 8, 16, 4)",opt3,0.0001,0.46
6080,symDHT,500,10,"(0.6, 0.2)",1.0,0.100,0.5,2,1,1,4,"(1, 16, 16, 4)",opt8,0.0040,0.46
11549,symDHT,500,10,"(0.6, 0.2)",1.0,0.001,0.5,2,1,1,4,"(1, 16, 16, 4)",opt3,0.0002,0.46

In [5]:
symhalfdht_kfold.shape[0]

17072

In [2]:
symhalfdhtabs_kfold = read_grid_search("results/tsinghua_11_symDHTabs_4_kfold_1") #not using arcsinh, only abs and flip
symhalfdhtabs_kfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
4686,symDHTabs,500,10,"(0.5, 0.5)",0.0,0.010,0.5,2,1,2,3,"(1, 8, 8, 4)",opt8,0.004,0.60
801,symDHTabs,500,10,"(0.2, 0.2)",1.0,0.100,0.5,3,2,1,5,"(1, 4, 8, 4)",opt8,0.001,0.58
19388,symDHTabs,500,10,"(0.3, 0.15)",0.0,0.100,0.5,3,2,2,5,"(1, 4, 8, 4)",opt8,0.004,0.58
2768,symDHTabs,500,10,"(0.5, 0.5)",1.0,0.010,0.5,3,2,1,5,"(1, 4, 8, 4)",opt8,0.001,0.58
19134,symDHTabs,500,10,"(0.3, 0.15)",2.0,0.001,0.5,3,2,1,5,"(1, 4, 8, 4)",opt8,0.001,0.58
18776,symDHTabs,500,10,"(0.2, 0.2)",1.0,0.100,0.5,3,2,2,5,"(1, 4, 8, 4)",opt8,0.004,0.56
21891,symDHTabs,500,10,"(0.6, 0.2)",1.0,0.001,0.5,2,1,3,3,"(1, 4, 8, 4)",opt8,0.001,0.56
11865,symDHTabs,500,10,"(0.3, 0.5)",2.0,0.100,0.5,3,2,1,5,"(1, 4, 8, 4)",opt8,0.004,0.56
3949,symDHTabs,500,10,"(0.5, 0.5)",2.0,0.100,0.5,3,2,1,5,"(1, 4, 8, 4)",opt8,0.004,0.56
2302,symDHTabs,500,10,"(0.3, 0.15)",2.0,0.100,0.5,3,2,1,5,"(1, 4, 8, 4)",opt8,0.004,0.56

In [3]:
symhalfdhtabs_kfold.shape[0]

22926

##### Evaluating all the subjects on the test set (retraining with train and val sets together) - redo

###### DFT

In [8]:
dft_final = read_grid_search("results/final_35_DFT_top1_4")
dft_final.sort_values("Test_Accuracy", ascending=False)

,Subject,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Test_Accuracy
3,32,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,1.000000
22,26,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,1.000000
5,22,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,1.000000
21,31,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,1.000000
12,4,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.916667
14,8,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.916667
17,20,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
24,1,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
20,30,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
18,35,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
34,13,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
10,27,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
32,9,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.750000
4,5,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.750000
11,28,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
8,16,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
27,21,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
0,24,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
13,34,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
19,14,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.583333
23,15,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
30,6,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
28,2,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
2,17,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
9,25,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
31,10,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.416667
1,18,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.416667
7,29,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.416667
15,23,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
29,11,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
16,19,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
6,33,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
33,12,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
26,3,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
25,7,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.250000

In [9]:
dft_final.loc[:,"Test_Accuracy"].mean()

0.6357143097142857

In [10]:
print(dft_final.sort_values("Test_Accuracy", ascending=False).to_latex())

\begin{tabular}{lrlrrrrrllrr}
\toprule
{} &  Subject & Function &  Time\_Off &  Window &  Overlap &  Levels &  Band\_Width & Neuron\_Configuration & Optimizer &  Learning\_Rate &  Test\_Accuracy \\
\midrule
3  &       32 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       1.000000 \\
22 &       26 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       1.000000 \\
5  &       22 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       1.000000 \\
21 &       31 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       1.000000 \\
12 &        4 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.916667 \\
14 &        8 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.916667 \\
17 &       20 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.833333 \\
24 &        1 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.833333 \\
20 &       30 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.833333 \\
18 &       35 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.833333 \\
34 &       13 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.833333 \\
10 &       27 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.833333 \\
32 &        9 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.750000 \\
4  &        5 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.750000 \\
11 &       28 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.666667 \\
8  &       16 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.666667 \\
27 &       21 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.666667 \\
0  &       24 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.666667 \\
13 &       34 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.666667 \\
19 &       14 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.583333 \\
23 &       15 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.500000 \\
30 &        6 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.500000 \\
28 &        2 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.500000 \\
2  &       17 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.500000 \\
9  &       25 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.500000 \\
31 &       10 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.416667 \\
1  &       18 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.416667 \\
7  &       29 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.416667 \\
15 &       23 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.333333 \\
29 &       11 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.333333 \\
16 &       19 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.333333 \\
6  &       33 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.333333 \\
33 &       12 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.333333 \\
26 &        3 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.333333 \\
25 &        7 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.250000 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_1096810/1869721132.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(dft_final.sort_values("Test_Accuracy", ascending=False).to_latex())

###### DHT

In [11]:
dht_final = read_grid_search("results/final_35_DHT_top1_4")
dht_final.sort_values("Test_Accuracy", ascending=False)

,Subject,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Test_Accuracy
14,31,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
27,13,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
6,22,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
24,32,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
32,26,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
16,8,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
2,4,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
3,35,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
4,20,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
22,1,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
10,5,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
8,16,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.833333
18,14,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.833333
29,27,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.833333
30,21,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
28,34,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
15,28,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
11,6,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
5,30,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
20,15,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.666667
9,24,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.666667
23,9,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.666667
13,17,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.583333
12,10,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.583333
25,3,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.583333
26,18,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.583333
31,33,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.500000
33,2,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.500000
0,25,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.416667
34,11,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.416667
21,23,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.416667
1,19,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.416667
7,29,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.333333
19,7,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.250000
17,12,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.250000

In [12]:
dht_final.loc[:,"Test_Accuracy"].mean()

0.7023809782857142

In [13]:
print(dht_final.sort_values("Test_Accuracy", ascending=False).to_latex())

\begin{tabular}{lrlrrrrrllrr}
\toprule
{} &  Subject & Function &  Time\_Off &  Window &  Overlap &  Levels &  Band\_Width & Neuron\_Configuration & Optimizer &  Learning\_Rate &  Test\_Accuracy \\
\midrule
14 &       31 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       1.000000 \\
27 &       13 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       1.000000 \\
6  &       22 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       1.000000 \\
24 &       32 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       1.000000 \\
32 &       26 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       1.000000 \\
16 &        8 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.916667 \\
2  &        4 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.916667 \\
3  &       35 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.916667 \\
4  &       20 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.916667 \\
22 &        1 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.916667 \\
10 &        5 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.916667 \\
8  &       16 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.833333 \\
18 &       14 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.833333 \\
29 &       27 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.833333 \\
30 &       21 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.750000 \\
28 &       34 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.750000 \\
15 &       28 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.750000 \\
11 &        6 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.750000 \\
5  &       30 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.750000 \\
20 &       15 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.666667 \\
9  &       24 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.666667 \\
23 &        9 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.666667 \\
13 &       17 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.583333 \\
12 &       10 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.583333 \\
25 &        3 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.583333 \\
26 &       18 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.583333 \\
31 &       33 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.500000 \\
33 &        2 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.500000 \\
0  &       25 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.416667 \\
34 &       11 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.416667 \\
21 &       23 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.416667 \\
1  &       19 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.416667 \\
7  &       29 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.333333 \\
19 &        7 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.250000 \\
17 &       12 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.250000 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_1096810/194379015.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(dht_final.sort_values("Test_Accuracy", ascending=False).to_latex())

In [2]:
dft_kfold12 = read_grid_search("results/grid_search_1_DFT_top10_4_kfold12")
dft_kfold12.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
816,DFT,0.5,2,1,1,2,"[4, 8]",opt8,0.0040,0.56
211,DFT,0.5,3,2,2,2,"[4, 8]",opt5,0.0002,0.54
227,DFT,0.5,3,2,2,2,"[4, 8]",opt4,0.0001,0.54
183,DFT,0.5,3,2,2,2,"[4, 8]",opt7,0.0001,0.54
337,DFT,0.5,3,2,3,2,"[4, 8]",opt7,0.0100,0.54
1080,DFT,0.5,3,2,1,1,"[4, 8]",opt7,0.0010,0.52
974,DFT,0.5,3,2,2,2,"[4, 8]",opt4,0.0002,0.52
864,DFT,0.5,3,2,1,1,"[4, 8]",opt5,0.0010,0.52
840,DFT,0.5,3,2,2,1,"[4, 8]",opt4,0.0001,0.52
833,DFT,0.5,3,2,1,2,"[4, 8]",opt8,0.0010,0.52

In [3]:
dht_kfold12 = read_grid_search("results/grid_search_1_DHT_top10_4_kfold12")
dht_kfold12.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
183,DHT,0.5,3,2,2,2,"[4, 8]",opt7,0.0001,0.58
1297,DHT,0.5,3,2,1,2,"[4, 8]",opt5,0.0010,0.56
227,DHT,0.5,3,2,2,2,"[4, 8]",opt4,0.0001,0.56
106,DHT,0.5,3,2,2,2,"[4, 8]",opt7,0.0002,0.56
162,DHT,0.5,3,2,2,2,"[4, 8]",opt5,0.0001,0.54
1721,DHT,0.5,3,2,3,2,"[4, 8]",opt5,0.0002,0.54
1589,DHT,0.5,3,2,1,2,"[4, 8]",opt4,0.0040,0.54
596,DHT,0.5,3,2,3,2,"[4, 8]",opt7,0.0002,0.54
1763,DHT,0.5,3,2,3,2,"[4, 8]",opt7,0.0001,0.54
1711,DHT,0.5,3,2,2,2,"[4, 8]",opt4,0.0040,0.54

In [2]:
dht_kfold11 = read_grid_search("results/grid_search_15_DHT_top10_4_kfold11")
dht_kfold11.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
347,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0002,0.561429
185,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0010,0.537333
357,DHT,0.5,3,2,2,1,"[4, 8]",opt8,0.0010,0.534667
117,DHT,0.5,3,2,2,1,"[4, 8]",opt8,0.0002,0.529333
59,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0001,0.521333
379,DHT,0.5,3,2,2,1,"[4, 8]",opt8,0.0001,0.514667
272,DHT,0.5,3,2,3,1,"[4, 8]",opt8,0.0002,0.508571
80,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0040,0.498667
88,DHT,0.5,3,2,2,1,"[4, 8]",opt8,0.0040,0.494667
103,DHT,0.5,3,2,1,1,"[4, 8]",opt4,0.0002,0.492000

In [3]:
dht_kfold24 = read_grid_search("results/grid_search_15_DHT_top10_4_kfold24")
dht_kfold24.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
301,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0001,0.76
152,DHT,0.5,3,2,2,1,"[4, 8]",opt8,0.0040,0.74
241,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0010,0.74
365,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0002,0.72
166,DHT,0.5,3,2,1,1,"[4, 8]",opt7,0.0002,0.72
248,DHT,0.5,3,2,1,1,"[4, 8]",opt4,0.0002,0.72
304,DHT,0.5,3,2,2,1,"[4, 8]",opt8,0.0010,0.72
323,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0040,0.70
312,DHT,0.5,3,2,3,1,"[4, 8]",opt8,0.0001,0.70
62,DHT,0.5,3,2,1,1,"[4, 8]",opt7,0.0001,0.68

In [4]:
dht_kfold19 = read_grid_search("results/grid_search_15_DHT_top10_4_kfold19")
dht_kfold19.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
353,DHT,0.5,3,2,3,1,"[4, 8]",opt5,0.0010,0.54
242,DHT,0.5,3,2,3,1,"[4, 8]",opt7,0.0002,0.54
298,DHT,0.5,3,2,2,1,"[4, 8]",opt5,0.0040,0.52
147,DHT,0.5,3,2,2,2,"[4, 8]",opt7,0.0001,0.52
238,DHT,0.5,3,2,1,1,"[4, 8]",opt7,0.0002,0.52
40,DHT,0.5,3,2,2,2,"[4, 8]",opt4,0.0001,0.52
239,DHT,0.5,3,2,1,1,"[4, 8]",opt4,0.0002,0.52
18,DHT,0.5,3,2,2,2,"[4, 8]",opt5,0.0001,0.52
360,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0002,0.52
258,DHT,0.5,3,2,3,1,"[4, 8]",opt4,0.0002,0.52

### Check results - Visual MNIST of the Brain

##### Binary MNIST

In [2]:
# here we classify digit and non-digit
dft_mnist = read_grid_search("results/mnist_1_DFT_2_kfold_1")
dft_mnist.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Training_Time,Mean_Accuracy
86,DFT,500,10,"(0.2, 0.2)",1.0,0.001,0.0,2,0,3,2,"(1, 4, 4, 2)",opt5,0.0040,120.024000,0.537222
235,DFT,500,10,"(0.3, 0.15)",1.0,0.001,0.0,2,0,3,2,"(1, 16, 16, 2)",opt7,0.0040,119.407000,0.533333
51,DFT,500,10,"(0.3, 0.5)",1.0,0.010,0.0,2,0,3,2,"(1, 4, 4, 2)",opt8,0.0100,115.722010,0.530556
1,DFT,500,10,"(0.3, 0.5)",0.0,0.010,0.0,2,0,3,2,"(1, 4, 4, 2)",opt7,0.0001,117.869995,0.529444
105,DFT,500,10,"(0.3, 0.15)",2.0,0.001,0.0,2,0,3,2,"(1, 32, 32, 2)",opt5,0.0100,120.650000,0.528889
135,DFT,500,10,"(0.5, 0.5)",1.0,0.010,0.0,2,0,3,2,"(1, 4, 4, 2)",opt4,0.0040,118.484010,0.526111
82,DFT,500,10,"(0.2, 0.2)",0.0,0.001,0.0,2,0,3,2,"(1, 32, 32, 2)",opt8,0.0010,117.440000,0.526111
72,DFT,500,10,"(0.5, 0.5)",2.0,0.001,0.0,2,0,3,2,"(1, 4, 8, 2)",opt1,0.0010,117.418020,0.526111
239,DFT,500,10,"(0.3, 0.5)",1.0,0.100,0.0,2,0,3,2,"(1, 4, 8, 2)",opt7,0.0100,118.369010,0.525556
80,DFT,500,10,"(0.6, 0.2)",0.0,0.100,0.0,2,0,3,2,"(1, 16, 32, 2)",opt3,0.0010,119.586000,0.522778

In [4]:
# here we classify digit and non-digit
dht_mnist = read_grid_search("results/mnist_1_DHT_2_kfold_1")
dht_mnist.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Training_Time,Mean_Accuracy
53,DHT,500,10,"(0.6, 0.2)",1.0,0.010,0.0,2,0,3,2,"(1, 4, 8, 2)",opt8,0.0100,115.695010,0.531667
217,DHT,500,10,"(0.3, 0.5)",1.0,0.001,0.0,2,0,3,2,"(1, 4, 4, 2)",opt1,0.0010,116.943010,0.527222
157,DHT,500,10,"(0.6, 0.2)",1.0,0.001,0.0,2,0,3,2,"(1, 4, 8, 2)",opt7,0.0010,118.092000,0.526111
108,DHT,500,10,"(0.2, 0.2)",1.0,0.001,0.0,2,0,3,2,"(1, 4, 8, 2)",opt1,0.0010,116.933010,0.525556
15,DHT,500,10,"(0.3, 0.5)",1.0,0.100,0.0,2,0,2,2,"(1, 4, 8, 2)",opt1,0.0010,116.992004,0.525556
72,DHT,500,10,"(0.2, 0.2)",1.0,0.100,0.0,2,0,3,2,"(1, 4, 4, 2)",opt5,0.0040,119.943990,0.522222
60,DHT,500,10,"(0.3, 0.5)",0.0,0.010,0.0,2,0,3,2,"(1, 8, 8, 2)",opt3,0.0001,118.887000,0.522222
129,DHT,500,10,"(0.6, 0.2)",1.0,0.001,0.0,2,0,2,2,"(1, 16, 32, 2)",opt7,0.0010,119.471000,0.521667
187,DHT,500,10,"(0.3, 0.5)",2.0,0.001,0.0,2,0,3,2,"(1, 32, 32, 2)",opt2,0.0010,121.189000,0.520556
23,DHT,500,10,"(0.2, 0.2)",2.0,0.010,0.0,2,0,2,2,"(1, 16, 32, 2)",opt3,0.0100,119.273000,0.520556

### Check results - BCI Competition Dataset IV 2a

#### K-Fold DFT (1 subject)

##### Subject 1

In [ ]:
bcic2akfold = read_grid_search("results_v3/bcic2a_1_DFT_4_Sum_kfold_1") #bcic2a_grid_search_{len(subjects)}_{f}_{n_classes}_kfold
bcic2akfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Training_Time,Mean_Accuracy
6813,DFT,500,10,"(0.3, 0.15)",0.0,0.010,0.0,5,0,3,2,"(1, 16, 32, 4)",opt5,0.001,20.016668,0.741667
1588,DFT,500,10,"(0.3, 0.5)",0.0,0.010,0.0,5,0,3,2,"(1, 16, 32, 4)",opt5,0.001,19.201668,0.741667
4534,DFT,500,10,"(0.3, 0.5)",0.0,0.100,0.0,5,0,3,4,"(1, 16, 16, 4)",opt3,0.004,19.806667,0.729167
3011,DFT,500,10,"(0.2, 0.2)",0.0,0.010,0.0,5,0,2,2,"(1, 32, 64, 4)",opt5,0.004,19.705000,0.725000
4518,DFT,500,10,"(0.5, 0.5)",0.0,0.010,0.0,5,0,3,3,"(1, 16, 32, 4)",opt4,0.004,19.426666,0.720833
7683,DFT,500,10,"(0.2, 0.2)",0.0,0.001,0.0,5,0,3,2,"(1, 16, 16, 4)",opt3,0.010,19.908333,0.720833
7358,DFT,500,10,"(0.3, 0.5)",0.0,0.010,0.0,5,0,3,2,"(1, 16, 32, 4)",opt5,0.004,19.798336,0.720833
4831,DFT,500,10,"(0.5, 0.5)",0.0,0.010,0.0,5,0,3,2,"(1, 32, 64, 4)",opt7,0.004,20.088335,0.716667
4364,DFT,500,10,"(0.2, 0.2)",0.0,0.100,0.0,5,0,3,3,"(1, 32, 64, 4)",opt3,0.004,19.481667,0.716667
5164,DFT,500,10,"(0.5, 0.5)",0.0,0.010,0.0,5,0,3,3,"(1, 32, 64, 4)",opt3,0.001,19.553333,0.716667

In [8]:
bcic2akfold.shape[0]

8947

In [4]:
print(bcic2akfold.sort_values("Mean_Accuracy",ascending=False).head(10).to_latex())

\begin{tabular}{llrrlrrrrrrrllrrr}
\toprule
{} & Function &  Epochs &  Batch\_Size &      Dropout &  FreqMean &  FreqStd &  Time\_Off &  Window &  Overlap &  Levels &  Band\_Width & Neuron\_Configuration & Optimizer &  Learning\_Rate &  Training\_Time &  Mean\_Accuracy \\
\midrule
6813 &      DFT &     500 &          10 &  (0.3, 0.15) &       0.0 &    0.010 &       0.0 &       5 &        0 &       3 &           2 &       (1, 16, 32, 4) &      opt5 &          0.001 &      20.016668 &       0.741667 \\
1588 &      DFT &     500 &          10 &   (0.3, 0.5) &       0.0 &    0.010 &       0.0 &       5 &        0 &       3 &           2 &       (1, 16, 32, 4) &      opt5 &          0.001 &      19.201668 &       0.741667 \\
4534 &      DFT &     500 &          10 &   (0.3, 0.5) &       0.0 &    0.100 &       0.0 &       5 &        0 &       3 &           4 &       (1, 16, 16, 4) &      opt3 &          0.004 &      19.806667 &       0.729167 \\
3011 &      DFT &     500 &          10 &   (0.2, 0.2) &       0.0 &    0.010 &       0.0 &       5 &        0 &       2 &           2 &       (1, 32, 64, 4) &      opt5 &          0.004 &      19.705000 &       0.725000 \\
4518 &      DFT &     500 &          10 &   (0.5, 0.5) &       0.0 &    0.010 &       0.0 &       5 &        0 &       3 &           3 &       (1, 16, 32, 4) &      opt4 &          0.004 &      19.426666 &       0.720833 \\
7683 &      DFT &     500 &          10 &   (0.2, 0.2) &       0.0 &    0.001 &       0.0 &       5 &        0 &       3 &           2 &       (1, 16, 16, 4) &      opt3 &          0.010 &      19.908333 &       0.720833 \\
7358 &      DFT &     500 &          10 &   (0.3, 0.5) &       0.0 &    0.010 &       0.0 &       5 &        0 &       3 &           2 &       (1, 16, 32, 4) &      opt5 &          0.004 &      19.798336 &       0.720833 \\
4831 &      DFT &     500 &          10 &   (0.5, 0.5) &       0.0 &    0.010 &       0.0 &       5 &        0 &       3 &           2 &       (1, 32, 64, 4) &      opt7 &          0.004 &      20.088335 &       0.716667 \\
4364 &      DFT &     500 &          10 &   (0.2, 0.2) &       0.0 &    0.100 &       0.0 &       5 &        0 &       3 &           3 &       (1, 32, 64, 4) &      opt3 &          0.004 &      19.481667 &       0.716667 \\
5164 &      DFT &     500 &          10 &   (0.5, 0.5) &       0.0 &    0.010 &       0.0 &       5 &        0 &       3 &           3 &       (1, 32, 64, 4) &      opt3 &          0.001 &      19.553333 &       0.716667 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_2171027/3088757517.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(bcic2akfold.sort_values("Mean_Accuracy",ascending=False).head(10).to_latex())

In [5]:
bcic2akfolddht = read_grid_search("results/bcic2a_1_DHT_4_kfold_1") #bcic2a_grid_search_{len(subjects)}_{f}_{n_classes}_kfold
bcic2akfolddht.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Training_Time,Mean_Accuracy
2018,DHT,500,10,"(0.3, 0.15)",0.0,0.001,0.0,5,0,2,5,"(1, 32, 64, 4)",opt3,0.0010,19.553335,0.687500
1105,DHT,500,10,"(0.6, 0.2)",1.0,0.010,0.0,5,0,2,5,"(1, 32, 64, 4)",opt5,0.0001,19.598333,0.687500
5754,DHT,500,10,"(0.6, 0.2)",0.0,0.100,0.0,5,0,2,5,"(1, 16, 16, 4)",opt5,0.0040,20.156668,0.683333
3942,DHT,500,10,"(0.2, 0.2)",0.0,0.001,0.0,5,0,2,5,"(1, 16, 16, 4)",opt3,0.0100,19.188334,0.683333
1266,DHT,500,10,"(0.3, 0.15)",2.0,0.100,0.0,5,0,2,5,"(1, 4, 8, 4)",opt4,0.0100,19.793335,0.683333
6242,DHT,500,10,"(0.6, 0.2)",2.0,0.001,0.0,5,0,2,5,"(1, 16, 32, 4)",opt7,0.0001,19.625000,0.679167
719,DHT,500,10,"(0.3, 0.15)",0.0,0.001,0.0,5,0,2,5,"(1, 32, 64, 4)",opt5,0.0001,19.881666,0.679167
1910,DHT,500,10,"(0.5, 0.5)",0.0,0.010,0.0,5,0,2,5,"(1, 16, 32, 4)",opt4,0.0001,19.321669,0.679167
805,DHT,500,10,"(0.2, 0.2)",0.0,0.100,0.0,5,0,2,5,"(1, 16, 32, 4)",opt3,0.0010,19.173332,0.679167
3091,DHT,500,10,"(0.5, 0.5)",1.0,0.010,0.0,5,0,2,5,"(1, 16, 16, 4)",opt4,0.0001,19.133333,0.675000

In [7]:
bcic2akfolddht.shape[0]

8975

In [6]:
print(bcic2akfolddht.sort_values("Mean_Accuracy",ascending=False).head(10).to_latex())

\begin{tabular}{llrrlrrrrrrrllrrr}
\toprule
{} & Function &  Epochs &  Batch\_Size &      Dropout &  FreqMean &  FreqStd &  Time\_Off &  Window &  Overlap &  Levels &  Band\_Width & Neuron\_Configuration & Optimizer &  Learning\_Rate &  Training\_Time &  Mean\_Accuracy \\
\midrule
2018 &      DHT &     500 &          10 &  (0.3, 0.15) &       0.0 &    0.001 &       0.0 &       5 &        0 &       2 &           5 &       (1, 32, 64, 4) &      opt3 &         0.0010 &      19.553335 &       0.687500 \\
1105 &      DHT &     500 &          10 &   (0.6, 0.2) &       1.0 &    0.010 &       0.0 &       5 &        0 &       2 &           5 &       (1, 32, 64, 4) &      opt5 &         0.0001 &      19.598333 &       0.687500 \\
5754 &      DHT &     500 &          10 &   (0.6, 0.2) &       0.0 &    0.100 &       0.0 &       5 &        0 &       2 &           5 &       (1, 16, 16, 4) &      opt5 &         0.0040 &      20.156668 &       0.683333 \\
3942 &      DHT &     500 &          10 &   (0.2, 0.2) &       0.0 &    0.001 &       0.0 &       5 &        0 &       2 &           5 &       (1, 16, 16, 4) &      opt3 &         0.0100 &      19.188334 &       0.683333 \\
1266 &      DHT &     500 &          10 &  (0.3, 0.15) &       2.0 &    0.100 &       0.0 &       5 &        0 &       2 &           5 &         (1, 4, 8, 4) &      opt4 &         0.0100 &      19.793335 &       0.683333 \\
6242 &      DHT &     500 &          10 &   (0.6, 0.2) &       2.0 &    0.001 &       0.0 &       5 &        0 &       2 &           5 &       (1, 16, 32, 4) &      opt7 &         0.0001 &      19.625000 &       0.679167 \\
719  &      DHT &     500 &          10 &  (0.3, 0.15) &       0.0 &    0.001 &       0.0 &       5 &        0 &       2 &           5 &       (1, 32, 64, 4) &      opt5 &         0.0001 &      19.881666 &       0.679167 \\
1910 &      DHT &     500 &          10 &   (0.5, 0.5) &       0.0 &    0.010 &       0.0 &       5 &        0 &       2 &           5 &       (1, 16, 32, 4) &      opt4 &         0.0001 &      19.321669 &       0.679167 \\
805  &      DHT &     500 &          10 &   (0.2, 0.2) &       0.0 &    0.100 &       0.0 &       5 &        0 &       2 &           5 &       (1, 16, 32, 4) &      opt3 &         0.0010 &      19.173332 &       0.679167 \\
3091 &      DHT &     500 &          10 &   (0.5, 0.5) &       1.0 &    0.010 &       0.0 &       5 &        0 &       2 &           5 &       (1, 16, 16, 4) &      opt4 &         0.0001 &      19.133333 &       0.675000 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_2171027/815820965.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(bcic2akfolddht.sort_values("Mean_Accuracy",ascending=False).head(10).to_latex())

##### Subject 4

In [7]:
bcic2a4kfold = read_grid_search("results/bcic2a_4_DFT_4_kfold_1") #bcic2a_grid_search_{len(subjects)}_{f}_{n_classes}_kfold
bcic2a4kfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Training_Time,Mean_Accuracy
1722,DFT,500,10,"(0.3, 0.5)",0.0,0.001,0.0,5,0,3,5,"(1, 16, 32, 4)",opt4,0.0010,19.723333,0.583333
5109,DFT,500,10,"(0.2, 0.2)",1.0,0.100,0.0,5,0,3,5,"(1, 16, 16, 4)",opt7,0.0001,19.396667,0.579167
8389,DFT,500,10,"(0.2, 0.2)",1.0,0.100,0.0,5,0,3,5,"(1, 16, 16, 4)",opt4,0.0001,19.590000,0.575000
578,DFT,500,10,"(0.3, 0.5)",0.0,0.100,0.0,5,0,3,5,"(1, 32, 64, 4)",opt5,0.0001,20.001667,0.570833
9261,DFT,500,10,"(0.3, 0.5)",1.0,0.001,0.0,5,0,3,5,"(1, 32, 64, 4)",opt7,0.0001,19.633335,0.570833
8315,DFT,500,10,"(0.6, 0.2)",0.0,0.001,0.0,5,0,3,5,"(1, 32, 64, 4)",opt7,0.0010,19.358334,0.566667
4042,DFT,500,10,"(0.5, 0.5)",2.0,0.100,0.0,5,0,3,5,"(1, 32, 64, 4)",opt4,0.0001,19.528334,0.562500
3036,DFT,500,10,"(0.3, 0.15)",0.0,0.100,0.0,5,0,3,5,"(1, 32, 64, 4)",opt3,0.0010,19.550001,0.558333
205,DFT,500,10,"(0.5, 0.5)",0.0,0.010,0.0,5,0,3,4,"(1, 32, 64, 4)",opt7,0.0010,19.535002,0.554167
72,DFT,500,10,"(0.5, 0.5)",2.0,0.001,0.0,5,0,3,5,"(1, 32, 64, 4)",opt5,0.0001,19.601667,0.554167

In [8]:
bcic2a4kfold.shape[0]

9362

In [10]:
bcic2a4kfolddht = read_grid_search("results/bcic2a_4_DHT_4_kfold_1") #bcic2a_grid_search_{len(subjects)}_{f}_{n_classes}_kfold
bcic2a4kfolddht.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Training_Time,Mean_Accuracy
8461,DHT,500,10,"(0.2, 0.2)",0.0,0.001,0.0,5,0,3,3,"(1, 16, 32, 4)",opt5,0.0010,19.736668,0.479167
3341,DHT,500,10,"(0.3, 0.15)",2.0,0.100,0.0,5,0,2,5,"(1, 32, 64, 4)",opt1,0.0100,18.550001,0.462500
7623,DHT,500,10,"(0.3, 0.5)",1.0,0.010,0.0,5,0,3,3,"(1, 32, 64, 4)",opt7,0.0001,19.295000,0.458333
9224,DHT,500,10,"(0.6, 0.2)",1.0,0.100,0.0,5,0,3,3,"(1, 32, 64, 4)",opt4,0.0001,19.953335,0.458333
5439,DHT,500,10,"(0.6, 0.2)",2.0,0.010,0.0,5,0,3,3,"(1, 32, 64, 4)",opt7,0.0001,19.406666,0.458333
5445,DHT,500,10,"(0.3, 0.15)",0.0,0.001,0.0,5,0,3,5,"(1, 16, 32, 4)",opt7,0.0010,19.561668,0.454167
6234,DHT,500,10,"(0.5, 0.5)",0.0,0.010,0.0,5,0,3,3,"(1, 16, 32, 4)",opt4,0.0001,19.188332,0.454167
417,DHT,500,10,"(0.3, 0.15)",0.0,0.010,0.0,5,0,3,3,"(1, 16, 32, 4)",opt4,0.0040,19.623335,0.454167
2372,DHT,500,10,"(0.2, 0.2)",0.0,0.100,0.0,5,0,3,3,"(1, 16, 32, 4)",opt3,0.0010,19.291666,0.454167
8517,DHT,500,10,"(0.5, 0.5)",0.0,0.010,0.0,5,0,3,5,"(1, 32, 64, 4)",opt7,0.0010,19.195000,0.450000

In [11]:
bcic2a4kfolddht.shape[0]

9371

#### K-Fold DHT (1 subject)

##### Subject 1

In [ ]:
bcic2akfold1 = read_grid_search("results_v3/bcic2a_1_DHT_4_Sum_kfold_1") #bcic2a_grid_search_{len(subjects)}_{f}_{n_classes}_kfold
bcic2akfold1.sort_values("Mean_Accuracy",ascending=False).head(10)

##### Subject 4

In [ ]:
bcic2akfold4 = read_grid_search("results_v3/bcic2a_4_DHT_4_Sum_kfold_1") #bcic2a_grid_search_{len(subjects)}_{f}_{n_classes}_kfold
bcic2akfold4.sort_values("Mean_Accuracy",ascending=False).head(10)

##### Final training with best config - redo

In [3]:
#### Classification using DHT and no validation set (training and evaluating on the test set)
bcic2a = read_grid_search("results/final_bcic2a_1_DHT_top10_4")
bcic2a.sort_values("Test_Accuracy",ascending=False).head(10)

,Subject,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Test_Accuracy
0,1,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.600695

In [4]:
bcic2a = read_grid_search("results/final_bcic2a_9_DHT_top10_4")
bcic2a.sort_values("Test_Accuracy",ascending=False).head(10)

,Subject,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Test_Accuracy
0,8,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.704861
6,3,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.697917
7,9,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.604167
2,1,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.600695
8,4,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.500000
3,2,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.489583
5,7,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.472222
1,6,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.385417
4,5,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.354167

In [5]:
bcic2a = read_grid_search("results/final_bcic2a_1_DFT_top10_4")
bcic2a.sort_values("Test_Accuracy",ascending=False).head(10)

,Subject,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Test_Accuracy
0,1,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.625

In [6]:
bcic2a = read_grid_search("results/final_bcic2a_9_DFT_top10_4")
bcic2a.sort_values("Test_Accuracy",ascending=False).head(10)

,Subject,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Test_Accuracy
5,8,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.697917
1,9,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.687500
3,3,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.687500
4,1,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.625000
7,4,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.527778
6,2,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.524306
8,7,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.468750
0,6,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.434028
2,5,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.420139