#### Setup

In [1]:
from main_functions.utils import read_grid_search

#### Check results - Tsinghua Dataset

##### k-fold DFT (1 subject) - correct

In [8]:
dft_kfold = read_grid_search("results/tsinghua_1_DFT_4_kfold_1")
dft_kfold.sort_values("Mean_Accuracy",ascending=False)#.head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
420,DFT,500,10,"(0.3, 0.15)",0.0,0.010,0.5,2,1,3,1,"(1, 16, 16, 4)",opt7,0.0100,0.90
1113,DFT,500,10,"(0.3, 0.5)",0.0,0.100,0.5,3,2,1,1,"(1, 8, 8, 4)",opt7,0.0040,0.86
1251,DFT,500,10,"(0.2, 0.2)",2.0,0.001,0.5,3,2,1,1,"(1, 16, 16, 4)",opt8,0.0040,0.86
96,DFT,500,10,"(0.3, 0.15)",0.0,0.001,0.5,3,2,2,1,"(1, 16, 16, 4)",opt4,0.0040,0.86
1232,DFT,500,10,"(0.5, 0.5)",0.0,0.010,0.5,3,2,1,4,"(1, 16, 16, 4)",opt4,0.0100,0.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,DFT,500,10,"(0.3, 0.5)",2.0,0.100,0.5,3,1,3,5,"(1, 4, 8, 4)",opt3,0.0040,NaN
1492,DFT,500,10,"(0.6, 0.2)",1.0,0.010,0.5,3,1,3,4,"(1, 4, 8, 4)",opt4,0.0100,NaN
1494,DFT,500,10,"(0.5, 0.5)",0.0,0.100,0.5,3,1,2,5,"(1, 16, 16, 4)",opt5,0.0002,NaN
1495,DFT,500,10,"(0.2, 0.2)",2.0,0.100,0.5,3,1,1,3,"(1, 8, 8, 4)",opt1,0.0010,NaN
1503,DFT,500,10,"(0.3, 0.5)",2.0,0.001,0.5,3,1,3,2,"(1, 8, 16, 4)",opt3,0.0040,NaN

In [ ]:
print(dft_kfold.sort_values("Mean_Accuracy",ascending=False).head(10).to_latex(label='tsinghua/dftkfold1', caption='Results of k-fold cross validation over trials for subject 1.'))

##### k-fold DHT (1 subject) - correct

In [7]:
dht_kfold = read_grid_search("results/tsinghua_1_DHT_4_kfold_1") #grid_search_1_DHT_top10_4_kfold
dht_kfold.sort_values("Mean_Accuracy",ascending=False)#.head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
734,DHT,500,10,"(0.2, 0.2)",2.0,0.010,0.5,3,2,1,1,"(1, 8, 8, 4)",opt8,0.0001,0.90
1288,DHT,500,10,"(0.2, 0.2)",1.0,0.100,0.5,3,2,1,1,"(1, 8, 16, 4)",opt8,0.0040,0.88
971,DHT,500,10,"(0.3, 0.15)",2.0,0.010,0.5,3,2,2,1,"(1, 8, 8, 4)",opt8,0.0001,0.84
1467,DHT,500,10,"(0.3, 0.5)",0.0,0.001,0.5,3,2,1,1,"(1, 8, 8, 4)",opt4,0.0002,0.82
458,DHT,500,10,"(0.5, 0.5)",0.0,0.100,0.5,3,2,1,2,"(1, 8, 8, 4)",opt3,0.0100,0.82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1459,DHT,500,10,"(0.6, 0.2)",0.0,0.100,0.5,3,1,3,5,"(1, 8, 8, 4)",opt1,0.0010,NaN
1470,DHT,500,10,"(0.6, 0.2)",2.0,0.010,0.5,3,1,1,3,"(1, 8, 16, 4)",opt3,0.0010,NaN
1471,DHT,500,10,"(0.3, 0.5)",2.0,0.100,0.5,3,1,2,3,"(1, 4, 8, 4)",opt5,0.0040,NaN
1473,DHT,500,10,"(0.3, 0.5)",2.0,0.001,0.5,3,1,1,4,"(1, 16, 16, 4)",opt1,0.0100,NaN
1483,DHT,500,10,"(0.3, 0.5)",1.0,0.001,0.5,3,1,2,4,"(1, 4, 8, 4)",opt4,0.0002,NaN

In [ ]:
print(dht_kfold.sort_values("Mean_Accuracy",ascending=False).head(10).to_latex())

##### Evaluating all the subjects on the test set (retraining with train and val sets together) - redo

###### DFT

In [8]:
dft_final = read_grid_search("results/final_35_DFT_top1_4")
dft_final.sort_values("Test_Accuracy", ascending=False)

,Subject,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Test_Accuracy
3,32,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,1.000000
22,26,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,1.000000
5,22,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,1.000000
21,31,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,1.000000
12,4,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.916667
14,8,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.916667
17,20,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
24,1,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
20,30,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
18,35,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
34,13,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
10,27,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
32,9,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.750000
4,5,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.750000
11,28,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
8,16,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
27,21,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
0,24,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
13,34,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
19,14,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.583333
23,15,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
30,6,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
28,2,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
2,17,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
9,25,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
31,10,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.416667
1,18,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.416667
7,29,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.416667
15,23,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
29,11,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
16,19,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
6,33,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
33,12,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
26,3,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
25,7,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.250000

In [9]:
dft_final.loc[:,"Test_Accuracy"].mean()

0.6357143097142857

In [10]:
print(dft_final.sort_values("Test_Accuracy", ascending=False).to_latex())

\begin{tabular}{lrlrrrrrllrr}
\toprule
{} &  Subject & Function &  Time\_Off &  Window &  Overlap &  Levels &  Band\_Width & Neuron\_Configuration & Optimizer &  Learning\_Rate &  Test\_Accuracy \\
\midrule
3  &       32 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       1.000000 \\
22 &       26 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       1.000000 \\
5  &       22 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       1.000000 \\
21 &       31 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       1.000000 \\
12 &        4 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.916667 \\
14 &        8 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.916667 \\
17 &       20 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.833333 \\
24 &        1 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.833333 \\
20 &       30 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.833333 \\
18 &       35 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.833333 \\
34 &       13 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.833333 \\
10 &       27 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.833333 \\
32 &        9 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.750000 \\
4  &        5 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.750000 \\
11 &       28 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.666667 \\
8  &       16 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.666667 \\
27 &       21 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.666667 \\
0  &       24 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.666667 \\
13 &       34 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.666667 \\
19 &       14 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.583333 \\
23 &       15 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.500000 \\
30 &        6 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.500000 \\
28 &        2 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.500000 \\
2  &       17 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.500000 \\
9  &       25 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.500000 \\
31 &       10 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.416667 \\
1  &       18 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.416667 \\
7  &       29 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.416667 \\
15 &       23 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.333333 \\
29 &       11 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.333333 \\
16 &       19 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.333333 \\
6  &       33 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.333333 \\
33 &       12 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.333333 \\
26 &        3 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.333333 \\
25 &        7 &      DFT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &          0.004 &       0.250000 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_1096810/1869721132.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(dft_final.sort_values("Test_Accuracy", ascending=False).to_latex())

###### DHT

In [11]:
dht_final = read_grid_search("results/final_35_DHT_top1_4")
dht_final.sort_values("Test_Accuracy", ascending=False)

,Subject,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Test_Accuracy
14,31,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
27,13,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
6,22,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
24,32,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
32,26,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
16,8,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
2,4,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
3,35,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
4,20,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
22,1,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
10,5,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
8,16,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.833333
18,14,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.833333
29,27,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.833333
30,21,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
28,34,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
15,28,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
11,6,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
5,30,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
20,15,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.666667
9,24,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.666667
23,9,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.666667
13,17,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.583333
12,10,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.583333
25,3,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.583333
26,18,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.583333
31,33,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.500000
33,2,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.500000
0,25,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.416667
34,11,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.416667
21,23,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.416667
1,19,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.416667
7,29,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.333333
19,7,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.250000
17,12,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.250000

In [12]:
dht_final.loc[:,"Test_Accuracy"].mean()

0.7023809782857142

In [13]:
print(dht_final.sort_values("Test_Accuracy", ascending=False).to_latex())

\begin{tabular}{lrlrrrrrllrr}
\toprule
{} &  Subject & Function &  Time\_Off &  Window &  Overlap &  Levels &  Band\_Width & Neuron\_Configuration & Optimizer &  Learning\_Rate &  Test\_Accuracy \\
\midrule
14 &       31 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       1.000000 \\
27 &       13 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       1.000000 \\
6  &       22 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       1.000000 \\
24 &       32 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       1.000000 \\
32 &       26 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       1.000000 \\
16 &        8 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.916667 \\
2  &        4 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.916667 \\
3  &       35 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.916667 \\
4  &       20 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.916667 \\
22 &        1 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.916667 \\
10 &        5 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.916667 \\
8  &       16 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.833333 \\
18 &       14 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.833333 \\
29 &       27 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.833333 \\
30 &       21 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.750000 \\
28 &       34 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.750000 \\
15 &       28 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.750000 \\
11 &        6 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.750000 \\
5  &       30 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.750000 \\
20 &       15 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.666667 \\
9  &       24 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.666667 \\
23 &        9 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.666667 \\
13 &       17 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.583333 \\
12 &       10 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.583333 \\
25 &        3 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.583333 \\
26 &       18 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.583333 \\
31 &       33 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.500000 \\
33 &        2 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.500000 \\
0  &       25 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.416667 \\
34 &       11 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.416667 \\
21 &       23 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.416667 \\
1  &       19 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.416667 \\
7  &       29 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.333333 \\
19 &        7 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.250000 \\
17 &       12 &      DHT &       0.5 &       3 &        2 &       1 &           1 &               [8, 8] &      opt1 &           0.01 &       0.250000 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_1096810/194379015.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(dht_final.sort_values("Test_Accuracy", ascending=False).to_latex())

##### Running k-fold for subject 12 (worst test accuracy) - maybe redo

In [2]:
dft_kfold12 = read_grid_search("results/grid_search_1_DFT_top10_4_kfold12")
dft_kfold12.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
816,DFT,0.5,2,1,1,2,"[4, 8]",opt8,0.0040,0.56
211,DFT,0.5,3,2,2,2,"[4, 8]",opt5,0.0002,0.54
227,DFT,0.5,3,2,2,2,"[4, 8]",opt4,0.0001,0.54
183,DFT,0.5,3,2,2,2,"[4, 8]",opt7,0.0001,0.54
337,DFT,0.5,3,2,3,2,"[4, 8]",opt7,0.0100,0.54
1080,DFT,0.5,3,2,1,1,"[4, 8]",opt7,0.0010,0.52
974,DFT,0.5,3,2,2,2,"[4, 8]",opt4,0.0002,0.52
864,DFT,0.5,3,2,1,1,"[4, 8]",opt5,0.0010,0.52
840,DFT,0.5,3,2,2,1,"[4, 8]",opt4,0.0001,0.52
833,DFT,0.5,3,2,1,2,"[4, 8]",opt8,0.0010,0.52

In [3]:
dht_kfold12 = read_grid_search("results/grid_search_1_DHT_top10_4_kfold12")
dht_kfold12.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
183,DHT,0.5,3,2,2,2,"[4, 8]",opt7,0.0001,0.58
1297,DHT,0.5,3,2,1,2,"[4, 8]",opt5,0.0010,0.56
227,DHT,0.5,3,2,2,2,"[4, 8]",opt4,0.0001,0.56
106,DHT,0.5,3,2,2,2,"[4, 8]",opt7,0.0002,0.56
162,DHT,0.5,3,2,2,2,"[4, 8]",opt5,0.0001,0.54
1721,DHT,0.5,3,2,3,2,"[4, 8]",opt5,0.0002,0.54
1589,DHT,0.5,3,2,1,2,"[4, 8]",opt4,0.0040,0.54
596,DHT,0.5,3,2,3,2,"[4, 8]",opt7,0.0002,0.54
1763,DHT,0.5,3,2,3,2,"[4, 8]",opt7,0.0001,0.54
1711,DHT,0.5,3,2,2,2,"[4, 8]",opt4,0.0040,0.54

##### Running k-fold for15 subjects (test accuracy < 75%) - maybe redo

In [2]:
dht_kfold11 = read_grid_search("results/grid_search_15_DHT_top10_4_kfold11")
dht_kfold11.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
347,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0002,0.561429
185,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0010,0.537333
357,DHT,0.5,3,2,2,1,"[4, 8]",opt8,0.0010,0.534667
117,DHT,0.5,3,2,2,1,"[4, 8]",opt8,0.0002,0.529333
59,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0001,0.521333
379,DHT,0.5,3,2,2,1,"[4, 8]",opt8,0.0001,0.514667
272,DHT,0.5,3,2,3,1,"[4, 8]",opt8,0.0002,0.508571
80,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0040,0.498667
88,DHT,0.5,3,2,2,1,"[4, 8]",opt8,0.0040,0.494667
103,DHT,0.5,3,2,1,1,"[4, 8]",opt4,0.0002,0.492000

In [3]:
dht_kfold24 = read_grid_search("results/grid_search_15_DHT_top10_4_kfold24")
dht_kfold24.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
301,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0001,0.76
152,DHT,0.5,3,2,2,1,"[4, 8]",opt8,0.0040,0.74
241,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0010,0.74
365,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0002,0.72
166,DHT,0.5,3,2,1,1,"[4, 8]",opt7,0.0002,0.72
248,DHT,0.5,3,2,1,1,"[4, 8]",opt4,0.0002,0.72
304,DHT,0.5,3,2,2,1,"[4, 8]",opt8,0.0010,0.72
323,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0040,0.70
312,DHT,0.5,3,2,3,1,"[4, 8]",opt8,0.0001,0.70
62,DHT,0.5,3,2,1,1,"[4, 8]",opt7,0.0001,0.68

In [4]:
dht_kfold19 = read_grid_search("results/grid_search_15_DHT_top10_4_kfold19")
dht_kfold19.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
353,DHT,0.5,3,2,3,1,"[4, 8]",opt5,0.0010,0.54
242,DHT,0.5,3,2,3,1,"[4, 8]",opt7,0.0002,0.54
298,DHT,0.5,3,2,2,1,"[4, 8]",opt5,0.0040,0.52
147,DHT,0.5,3,2,2,2,"[4, 8]",opt7,0.0001,0.52
238,DHT,0.5,3,2,1,1,"[4, 8]",opt7,0.0002,0.52
40,DHT,0.5,3,2,2,2,"[4, 8]",opt4,0.0001,0.52
239,DHT,0.5,3,2,1,1,"[4, 8]",opt4,0.0002,0.52
18,DHT,0.5,3,2,2,2,"[4, 8]",opt5,0.0001,0.52
360,DHT,0.5,3,2,1,1,"[4, 8]",opt8,0.0002,0.52
258,DHT,0.5,3,2,3,1,"[4, 8]",opt4,0.0002,0.52

#### Check results - Visual MNIST of the Brain

##### Binary MNIST

In [2]:
# here we classify digit and non-digit
dft_mnist = read_grid_search("results/mnist_1_DFT_2_kfold_1")
dft_mnist.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Training_Time,Mean_Accuracy
86,DFT,500,10,"(0.2, 0.2)",1.0,0.001,0.0,2,0,3,2,"(1, 4, 4, 2)",opt5,0.0040,120.024000,0.537222
235,DFT,500,10,"(0.3, 0.15)",1.0,0.001,0.0,2,0,3,2,"(1, 16, 16, 2)",opt7,0.0040,119.407000,0.533333
51,DFT,500,10,"(0.3, 0.5)",1.0,0.010,0.0,2,0,3,2,"(1, 4, 4, 2)",opt8,0.0100,115.722010,0.530556
1,DFT,500,10,"(0.3, 0.5)",0.0,0.010,0.0,2,0,3,2,"(1, 4, 4, 2)",opt7,0.0001,117.869995,0.529444
105,DFT,500,10,"(0.3, 0.15)",2.0,0.001,0.0,2,0,3,2,"(1, 32, 32, 2)",opt5,0.0100,120.650000,0.528889
135,DFT,500,10,"(0.5, 0.5)",1.0,0.010,0.0,2,0,3,2,"(1, 4, 4, 2)",opt4,0.0040,118.484010,0.526111
82,DFT,500,10,"(0.2, 0.2)",0.0,0.001,0.0,2,0,3,2,"(1, 32, 32, 2)",opt8,0.0010,117.440000,0.526111
72,DFT,500,10,"(0.5, 0.5)",2.0,0.001,0.0,2,0,3,2,"(1, 4, 8, 2)",opt1,0.0010,117.418020,0.526111
239,DFT,500,10,"(0.3, 0.5)",1.0,0.100,0.0,2,0,3,2,"(1, 4, 8, 2)",opt7,0.0100,118.369010,0.525556
80,DFT,500,10,"(0.6, 0.2)",0.0,0.100,0.0,2,0,3,2,"(1, 16, 32, 2)",opt3,0.0010,119.586000,0.522778

In [4]:
# here we classify digit and non-digit
dht_mnist = read_grid_search("results/mnist_1_DHT_2_kfold_1")
dht_mnist.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Training_Time,Mean_Accuracy
53,DHT,500,10,"(0.6, 0.2)",1.0,0.010,0.0,2,0,3,2,"(1, 4, 8, 2)",opt8,0.0100,115.695010,0.531667
217,DHT,500,10,"(0.3, 0.5)",1.0,0.001,0.0,2,0,3,2,"(1, 4, 4, 2)",opt1,0.0010,116.943010,0.527222
157,DHT,500,10,"(0.6, 0.2)",1.0,0.001,0.0,2,0,3,2,"(1, 4, 8, 2)",opt7,0.0010,118.092000,0.526111
108,DHT,500,10,"(0.2, 0.2)",1.0,0.001,0.0,2,0,3,2,"(1, 4, 8, 2)",opt1,0.0010,116.933010,0.525556
15,DHT,500,10,"(0.3, 0.5)",1.0,0.100,0.0,2,0,2,2,"(1, 4, 8, 2)",opt1,0.0010,116.992004,0.525556
72,DHT,500,10,"(0.2, 0.2)",1.0,0.100,0.0,2,0,3,2,"(1, 4, 4, 2)",opt5,0.0040,119.943990,0.522222
60,DHT,500,10,"(0.3, 0.5)",0.0,0.010,0.0,2,0,3,2,"(1, 8, 8, 2)",opt3,0.0001,118.887000,0.522222
129,DHT,500,10,"(0.6, 0.2)",1.0,0.001,0.0,2,0,2,2,"(1, 16, 32, 2)",opt7,0.0010,119.471000,0.521667
187,DHT,500,10,"(0.3, 0.5)",2.0,0.001,0.0,2,0,3,2,"(1, 32, 32, 2)",opt2,0.0010,121.189000,0.520556
23,DHT,500,10,"(0.2, 0.2)",2.0,0.010,0.0,2,0,2,2,"(1, 16, 32, 2)",opt3,0.0100,119.273000,0.520556

#### Check results - BCI Competition Dataset IV 2a

##### K-Fold cross validation over trials with dropout, freqmean and freqstd variation - correct

In [2]:
bcic2akfold = read_grid_search("results/bcic2a_1_DFT_4_kfold_1") #bcic2a_grid_search_{len(subjects)}_{f}_{n_classes}_kfold
bcic2akfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Training_Time,Mean_Accuracy
112,DFT,500,10,"(0.3, 0.5)",0.0,0.010,0.0,5,0,3,2,"(1, 16, 32, 4)",opt5,0.0010,19.201668,0.741667
45,DFT,500,10,"(0.3, 0.15)",0.0,0.010,0.0,5,0,3,3,"(1, 16, 32, 4)",opt4,0.0001,19.118336,0.708333
611,DFT,500,10,"(0.3, 0.15)",0.0,0.010,0.0,5,0,3,4,"(1, 32, 64, 4)",opt4,0.0010,19.063334,0.708333
101,DFT,500,10,"(0.6, 0.2)",0.0,0.001,0.0,5,0,3,2,"(1, 16, 16, 4)",opt7,0.0010,19.091665,0.704167
466,DFT,500,10,"(0.3, 0.5)",0.0,0.001,0.0,5,0,3,3,"(1, 8, 16, 4)",opt3,0.0040,19.041668,0.700000
67,DFT,500,10,"(0.3, 0.5)",0.0,0.010,0.0,5,0,3,2,"(1, 4, 8, 4)",opt4,0.0010,18.963333,0.700000
432,DFT,500,10,"(0.2, 0.2)",1.0,0.100,0.0,5,0,3,5,"(1, 16, 32, 4)",opt8,0.0010,18.869999,0.700000
303,DFT,500,10,"(0.2, 0.2)",0.0,0.100,0.0,5,0,3,3,"(1, 32, 64, 4)",opt4,0.0040,19.263336,0.700000
534,DFT,500,10,"(0.5, 0.5)",0.0,0.001,0.0,5,0,2,4,"(1, 8, 16, 4)",opt3,0.0010,19.010000,0.700000
186,DFT,500,10,"(0.5, 0.5)",1.0,0.001,0.0,5,0,3,2,"(1, 32, 64, 4)",opt5,0.0001,19.716667,0.695833

In [4]:
bcic2akfold = read_grid_search("results/bcic2a_1_DHT_4_kfold_1") #bcic2a_grid_search_{len(subjects)}_{f}_{n_classes}_kfold
bcic2akfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Dropout,FreqMean,FreqStd,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Training_Time,Mean_Accuracy
276,DHT,500,10,"(0.6, 0.2)",0.0,0.001,0.0,5,0,3,1,"(1, 16, 16, 4)",opt5,0.0040,19.780000,0.683333
50,DHT,500,10,"(0.2, 0.2)",0.0,0.100,0.0,5,0,2,5,"(1, 16, 32, 4)",opt3,0.0010,19.173332,0.679167
60,DHT,500,10,"(0.3, 0.5)",1.0,0.001,0.0,5,0,2,5,"(1, 32, 64, 4)",opt3,0.0040,18.725002,0.675000
296,DHT,500,10,"(0.3, 0.15)",1.0,0.100,0.0,5,0,3,5,"(1, 32, 64, 4)",opt4,0.0001,19.210000,0.666667
598,DHT,500,10,"(0.6, 0.2)",1.0,0.010,0.0,5,0,3,5,"(1, 32, 64, 4)",opt5,0.0001,19.436668,0.654167
15,DHT,500,10,"(0.3, 0.15)",1.0,0.010,0.0,5,0,2,5,"(1, 32, 64, 4)",opt3,0.0040,18.886667,0.654167
576,DHT,500,10,"(0.5, 0.5)",2.0,0.001,0.0,5,0,2,5,"(1, 16, 32, 4)",opt5,0.0001,19.503334,0.654167
300,DHT,500,10,"(0.3, 0.5)",0.0,0.010,0.0,5,0,3,1,"(1, 16, 16, 4)",opt5,0.0100,19.110000,0.654167
132,DHT,500,10,"(0.6, 0.2)",0.0,0.010,0.0,5,0,3,5,"(1, 16, 32, 4)",opt4,0.0040,18.806667,0.654167
541,DHT,500,10,"(0.3, 0.15)",0.0,0.010,0.0,5,0,2,5,"(1, 16, 32, 4)",opt3,0.0040,19.280003,0.654167

##### K-Fold cross validation over trials (no dropout variation - fixed [0.30, 0.15]) - ignore

In [2]:
bcic2akfold = read_grid_search("results/bcic2a_grid_search_1_DHT_4_kfold") #bcic2a_grid_search_{len(subjects)}_{f}_{n_classes}_kfold
bcic2akfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Training_Time,Mean_Accuracy
226,DHT,500,10,0.0,5,0,3,5,"[64, 64]",opt3,0.0010,19.055000,0.687500
149,DHT,500,10,0.0,5,0,3,5,"[64, 64]",opt5,0.0010,19.303333,0.683333
1093,DHT,500,10,0.0,5,0,3,5,"[64, 64]",opt3,0.0001,18.801666,0.679167
2415,DHT,500,10,0.0,5,0,3,5,"[64, 64]",opt3,0.0010,18.851667,0.675000
551,DHT,500,10,0.0,5,0,3,5,"[64, 64]",opt3,0.0010,19.355000,0.670833
2151,DHT,500,10,0.0,5,0,3,5,"[64, 64]",opt5,0.0001,19.346666,0.670833
319,DHT,500,10,0.0,5,0,2,5,"[64, 64]",opt7,0.0010,19.031666,0.666667
1081,DHT,500,10,0.0,5,0,2,5,"[64, 64]",opt5,0.0001,19.436668,0.666667
1158,DHT,500,10,0.0,5,0,2,5,"[64, 64]",opt7,0.0001,18.750000,0.666667
941,DHT,500,10,0.0,5,0,2,5,"[64, 64]",opt4,0.0040,19.100000,0.666667

In [20]:
print(bcic2akfold.sort_values("Mean_Accuracy",ascending=False).head(10).to_latex())

\begin{tabular}{llrrrrrrrllrrr}
\toprule
{} & Function &  Epochs &  Batch\_Size &  Time\_Off &  Window &  Overlap &  Levels &  Band\_Width & Neuron\_Configuration & Optimizer &  Learning\_Rate &  Training\_Time &  Mean\_Accuracy \\
\midrule
226  &      DHT &     500 &          10 &       0.0 &       5 &        0 &       3 &           5 &             [64, 64] &      opt3 &         0.0010 &      19.055000 &       0.687500 \\
149  &      DHT &     500 &          10 &       0.0 &       5 &        0 &       3 &           5 &             [64, 64] &      opt5 &         0.0010 &      19.303333 &       0.683333 \\
1093 &      DHT &     500 &          10 &       0.0 &       5 &        0 &       3 &           5 &             [64, 64] &      opt3 &         0.0001 &      18.801666 &       0.679167 \\
2415 &      DHT &     500 &          10 &       0.0 &       5 &        0 &       3 &           5 &             [64, 64] &      opt3 &         0.0010 &      18.851667 &       0.675000 \\
551  &      DHT &     500 &          10 &       0.0 &       5 &        0 &       3 &           5 &             [64, 64] &      opt3 &         0.0010 &      19.355000 &       0.670833 \\
2151 &      DHT &     500 &          10 &       0.0 &       5 &        0 &       3 &           5 &             [64, 64] &      opt5 &         0.0001 &      19.346666 &       0.670833 \\
319  &      DHT &     500 &          10 &       0.0 &       5 &        0 &       2 &           5 &             [64, 64] &      opt7 &         0.0010 &      19.031666 &       0.666667 \\
1081 &      DHT &     500 &          10 &       0.0 &       5 &        0 &       2 &           5 &             [64, 64] &      opt5 &         0.0001 &      19.436668 &       0.666667 \\
1158 &      DHT &     500 &          10 &       0.0 &       5 &        0 &       2 &           5 &             [64, 64] &      opt7 &         0.0001 &      18.750000 &       0.666667 \\
941  &      DHT &     500 &          10 &       0.0 &       5 &        0 &       2 &           5 &             [64, 64] &      opt4 &         0.0040 &      19.100000 &       0.666667 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_1096810/3088757517.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(bcic2akfold.sort_values("Mean_Accuracy",ascending=False).head(10).to_latex())

In [17]:
bcic2akfold = read_grid_search("results/bcic2a_grid_search_1_DFT_4_kfold") #bcic2a_grid_search_{len(subjects)}_{f}_{n_classes}_kfold
bcic2akfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Epochs,Batch_Size,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Training_Time,Mean_Accuracy
898,DFT,500,10,0.0,5,0,2,5,"[64, 64]",opt8,0.0010,18.888334,0.708333
2130,DFT,500,10,0.0,5,0,2,4,"[64, 64]",opt4,0.0010,18.956665,0.704167
403,DFT,500,10,0.0,5,0,3,4,"[64, 64]",opt3,0.0010,19.686666,0.704167
1049,DFT,500,10,0.0,5,0,3,2,"[64, 64]",opt4,0.0010,19.168333,0.704167
2438,DFT,500,10,0.0,5,0,3,2,"[64, 64]",opt3,0.0100,19.226667,0.700000
23,DFT,500,10,0.0,5,0,3,4,"[64, 64]",opt4,0.0001,19.313335,0.700000
1306,DFT,500,10,0.0,5,0,3,4,"[64, 64]",opt5,0.0001,19.690000,0.700000
1326,DFT,500,10,0.0,5,0,2,4,"[64, 64]",opt4,0.0001,19.248333,0.700000
2443,DFT,500,10,0.0,5,0,3,2,"[64, 64]",opt5,0.0001,19.566668,0.695833
51,DFT,500,10,0.0,5,0,3,4,"[64, 64]",opt5,0.0001,19.118334,0.695833

In [18]:
print(bcic2akfold.sort_values("Mean_Accuracy",ascending=False).head(10).to_latex())

\begin{tabular}{llrrrrrrrllrrr}
\toprule
{} & Function &  Epochs &  Batch\_Size &  Time\_Off &  Window &  Overlap &  Levels &  Band\_Width & Neuron\_Configuration & Optimizer &  Learning\_Rate &  Training\_Time &  Mean\_Accuracy \\
\midrule
898  &      DFT &     500 &          10 &       0.0 &       5 &        0 &       2 &           5 &             [64, 64] &      opt8 &         0.0010 &      18.888334 &       0.708333 \\
2130 &      DFT &     500 &          10 &       0.0 &       5 &        0 &       2 &           4 &             [64, 64] &      opt4 &         0.0010 &      18.956665 &       0.704167 \\
403  &      DFT &     500 &          10 &       0.0 &       5 &        0 &       3 &           4 &             [64, 64] &      opt3 &         0.0010 &      19.686666 &       0.704167 \\
1049 &      DFT &     500 &          10 &       0.0 &       5 &        0 &       3 &           2 &             [64, 64] &      opt4 &         0.0010 &      19.168333 &       0.704167 \\
2438 &      DFT &     500 &          10 &       0.0 &       5 &        0 &       3 &           2 &             [64, 64] &      opt3 &         0.0100 &      19.226667 &       0.700000 \\
23   &      DFT &     500 &          10 &       0.0 &       5 &        0 &       3 &           4 &             [64, 64] &      opt4 &         0.0001 &      19.313335 &       0.700000 \\
1306 &      DFT &     500 &          10 &       0.0 &       5 &        0 &       3 &           4 &             [64, 64] &      opt5 &         0.0001 &      19.690000 &       0.700000 \\
1326 &      DFT &     500 &          10 &       0.0 &       5 &        0 &       2 &           4 &             [64, 64] &      opt4 &         0.0001 &      19.248333 &       0.700000 \\
2443 &      DFT &     500 &          10 &       0.0 &       5 &        0 &       3 &           2 &             [64, 64] &      opt5 &         0.0001 &      19.566668 &       0.695833 \\
51   &      DFT &     500 &          10 &       0.0 &       5 &        0 &       3 &           4 &             [64, 64] &      opt5 &         0.0001 &      19.118334 &       0.695833 \\
\bottomrule
\end{tabular}

/tmp/ipykernel_1096810/3088757517.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(bcic2akfold.sort_values("Mean_Accuracy",ascending=False).head(10).to_latex())

##### Final training with best config - redo

In [3]:
#### Classification using DHT and no validation set (training and evaluating on the test set)
bcic2a = read_grid_search("results/final_bcic2a_1_DHT_top10_4")
bcic2a.sort_values("Test_Accuracy",ascending=False).head(10)

,Subject,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Test_Accuracy
0,1,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.600695

In [4]:
bcic2a = read_grid_search("results/final_bcic2a_9_DHT_top10_4")
bcic2a.sort_values("Test_Accuracy",ascending=False).head(10)

,Subject,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Test_Accuracy
0,8,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.704861
6,3,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.697917
7,9,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.604167
2,1,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.600695
8,4,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.500000
3,2,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.489583
5,7,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.472222
1,6,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.385417
4,5,DHT,0.0,5,0,3,5,"[64, 64]",opt3,0.001,0.354167

In [5]:
bcic2a = read_grid_search("results/final_bcic2a_1_DFT_top10_4")
bcic2a.sort_values("Test_Accuracy",ascending=False).head(10)

,Subject,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Test_Accuracy
0,1,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.625

In [6]:
bcic2a = read_grid_search("results/final_bcic2a_9_DFT_top10_4")
bcic2a.sort_values("Test_Accuracy",ascending=False).head(10)

,Subject,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Test_Accuracy
5,8,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.697917
1,9,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.687500
3,3,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.687500
4,1,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.625000
7,4,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.527778
6,2,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.524306
8,7,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.468750
0,6,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.434028
2,5,DFT,0.0,5,0,2,5,"[64, 64]",opt8,0.001,0.420139