#### Setup

In [1]:
from main_functions.utils import read_grid_search

#### Check top 10 results - DFT

#### 1 subject

In [2]:
b = read_grid_search("results/grid_search_1_DFT_top10_4")
b.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
1244,DFT,0.5,3,1,1,1,"(16, 16)",opt4,0.0001,0.900000
338,DFT,0.5,3,2,1,1,"(16, 16)",opt4,0.0001,0.866667
1293,DFT,0.5,3,2,2,1,"(16, 16)",opt5,0.0001,0.866667
230,DFT,0.5,3,2,1,2,"(16, 16)",opt4,0.0001,0.850000
457,DFT,0.5,3,2,3,1,"(16, 16)",opt4,0.0001,0.850000
2681,DFT,0.5,3,2,2,1,"(16, 16)",opt4,0.0001,0.833333
2162,DFT,0.5,3,2,3,1,"(16, 16)",opt5,0.0001,0.833333
1241,DFT,0.5,3,1,3,1,"(16, 16)",opt5,0.0001,0.825000
93,DFT,0.5,3,1,1,1,"(16, 16)",opt5,0.0010,0.825000
2633,DFT,0.5,3,1,1,1,"(16, 16)",opt5,0.0001,0.825000

##### 35 subjects

In [5]:
e = read_grid_search("results/grid_search_35_DFT_top10_4")
e.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
24,DFT,0.5,2,1,1,2,"[16, 16]",opt5,0.0010,0.653929
21,DFT,0.5,2,1,1,2,"[16, 16]",opt4,0.0001,0.650000
26,DFT,0.5,2,1,1,2,"[16, 16]",opt5,0.0001,0.644286
13,DFT,0.5,2,1,1,1,"[16, 16]",opt5,0.0010,0.612857
10,DFT,0.5,2,1,1,1,"[16, 16]",opt4,0.0001,0.607500
1,DFT,0.5,2,1,2,1,"[16, 16]",opt4,0.0010,0.605357
23,DFT,0.5,3,2,2,2,"[16, 16]",opt5,0.0001,0.597143
14,DFT,0.5,3,2,1,2,"[16, 16]",opt5,0.0001,0.595714
9,DFT,0.5,3,2,2,2,"[16, 16]",opt4,0.0010,0.591905
11,DFT,0.5,2,1,3,2,"[16, 16]",opt4,0.0010,0.590000

#### Check top 10 results - DHT

##### 1 subject

In [28]:
c = read_grid_search("results/grid_search_1_DHT_top10_4")
c.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
834,DHT,0.5,3,1,1,1,"(16, 16)",opt4,0.0001,0.800000
747,DHT,0.5,3,1,2,1,"(16, 16)",opt4,0.0001,0.800000
1241,DHT,0.5,3,2,1,1,"(16, 16)",opt4,0.0001,0.783333
420,DHT,0.5,3,1,1,1,"(16, 16)",opt5,0.0001,0.775000
284,DHT,0.5,3,2,2,1,"(16, 16)",opt5,0.0001,0.750000
631,DHT,0.5,3,2,1,1,"(16, 16)",opt5,0.0001,0.750000
1939,DHT,0.5,2,1,1,2,"(16, 16)",opt4,0.0001,0.750000
344,DHT,0.5,3,2,1,1,"(16, 16)",opt4,0.0001,0.750000
2265,DHT,0.5,2,1,1,2,"(16, 16)",opt5,0.0001,0.750000
86,DHT,0.5,3,1,1,1,"(16, 16)",opt5,0.0010,0.750000

##### 35 subjects

In [4]:
d = read_grid_search("results/grid_search_35_DHT_top10_4")
d.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
24,DHT,0.5,2,1,1,2,"[16, 16]",opt5,0.0001,0.609643
21,DHT,0.5,2,1,3,1,"[16, 16]",opt4,0.0010,0.577857
14,DHT,0.5,2,1,3,1,"[16, 16]",opt4,0.0001,0.576786
12,DHT,0.5,2,1,3,2,"[16, 16]",opt4,0.0010,0.575000
25,DHT,0.5,2,1,3,1,"[16, 16]",opt5,0.0001,0.572500
22,DHT,0.5,2,1,3,2,"[16, 16]",opt4,0.0001,0.572143
18,DHT,0.5,2,1,2,1,"[16, 16]",opt5,0.0010,0.569286
0,DHT,0.5,3,2,1,2,"[16, 16]",opt5,0.0010,0.568571
19,DHT,0.5,2,1,2,2,"[16, 16]",opt5,0.0001,0.566786
27,DHT,0.5,3,2,2,1,"[16, 16]",opt4,0.0010,0.566667

#### Check results - k-fold DFT (1 subject)

In [2]:
dft_kfold = read_grid_search("results/grid_search_1_DFT_top10_4_kfold")
dft_kfold.sort_values("Mean_Accuracy",ascending=False).head(10)

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
1798,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.0040,0.90
940,DFT,0.5,3,2,1,1,"[8, 8]",opt8,0.0002,0.90
671,DFT,0.5,3,2,3,1,"[8, 8]",opt8,0.0002,0.88
1279,DFT,0.5,3,2,1,1,"[8, 8]",opt8,0.0001,0.88
127,DFT,0.5,3,2,1,1,"[8, 8]",opt7,0.0001,0.86
796,DFT,0.5,3,2,1,1,"[8, 8]",opt4,0.0001,0.86
971,DFT,0.5,3,2,1,1,"[8, 16]",opt8,0.0010,0.86
140,DFT,0.5,3,2,1,1,"[8, 16]",opt8,0.0040,0.86
101,DFT,0.5,3,2,2,1,"[8, 16]",opt8,0.0040,0.86
120,DFT,0.5,3,2,1,1,"[8, 8]",opt4,0.0002,0.86

#### Check results - k-fold DHT (1 subject)

In [3]:
dht_kfold = read_grid_search("results/grid_search_1_DHT_top10_4_kfold")
dht_kfold.sort_values("Mean_Accuracy",ascending=False).head(10) #2=71.30

,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Mean_Accuracy
940,DHT,0.5,3,2,1,1,"[8, 8]",opt8,0.0002,0.90
298,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.0100,0.90
1279,DHT,0.5,3,2,1,1,"[8, 8]",opt8,0.0001,0.90
1246,DHT,0.5,3,2,2,1,"[8, 8]",opt8,0.0010,0.90
1795,DHT,0.5,3,2,2,1,"[8, 8]",opt1,0.0100,0.88
1103,DHT,0.5,3,2,2,1,"[8, 8]",opt8,0.0002,0.88
121,DHT,0.5,3,2,1,1,"[8, 8]",opt8,0.0040,0.86
796,DHT,0.5,3,2,1,1,"[8, 8]",opt4,0.0001,0.86
1798,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.0040,0.86
1184,DHT,0.5,3,2,1,1,"[8, 8]",opt7,0.0002,0.86

#### Evaluating all the subjects on the test set (retraining with train and val sets together)

##### DFT

In [57]:
dft_final = read_grid_search("results/final_35_DFT_top1_4")
dft_final.sort_values("Test_Accuracy", ascending=False)

,Subject,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Test_Accuracy
3,32,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,1.000000
22,26,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,1.000000
5,22,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,1.000000
21,31,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,1.000000
12,4,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.916667
14,8,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.916667
17,20,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
24,1,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
20,30,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
18,35,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
34,13,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
10,27,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.833333
32,9,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.750000
4,5,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.750000
11,28,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
8,16,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
27,21,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
0,24,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
13,34,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.666667
19,14,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.583333
23,15,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
30,6,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
28,2,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
2,17,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
9,25,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.500000
31,10,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.416667
1,18,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.416667
7,29,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.416667
15,23,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
29,11,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
16,19,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
6,33,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
33,12,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
26,3,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.333333
25,7,DFT,0.5,3,2,1,1,"[8, 8]",opt1,0.004,0.250000

In [59]:
dft_final.loc[:,"Test_Accuracy"].mean()

0.6357143097142857

##### DHT

In [48]:
dht_final = read_grid_search("results/final_35_DHT_top1_4")
dht_final.sort_values("Test_Accuracy", ascending=False)

,Subject,Function,Time_Off,Window,Overlap,Levels,Band_Width,Neuron_Configuration,Optimizer,Learning_Rate,Test_Accuracy
14,31,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
27,13,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
6,22,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
24,32,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
32,26,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,1.000000
16,8,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
2,4,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
3,35,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
4,20,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
22,1,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
10,5,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.916667
8,16,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.833333
18,14,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.833333
29,27,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.833333
30,21,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
28,34,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
15,28,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
11,6,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
5,30,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.750000
20,15,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.666667
9,24,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.666667
23,9,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.666667
13,17,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.583333
12,10,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.583333
25,3,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.583333
26,18,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.583333
31,33,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.500000
33,2,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.500000
0,25,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.416667
34,11,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.416667
21,23,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.416667
1,19,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.416667
7,29,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.333333
19,7,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.250000
17,12,DHT,0.5,3,2,1,1,"[8, 8]",opt1,0.01,0.250000

In [61]:
dht_final.loc[:,"Test_Accuracy"].mean()

0.7023809782857142